const mongoose = require("mongoose");

const listingSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },

    category: {
      type: String,
      required: true,
      enum: [
        "pg",
        "tiffin",
        "car-rental",
        "bike-rental",
        "laundry",
        "packers-movers",
        "parking",
        "room-rental",
        "stay",
        "eat",
        "live",
        "move",
        "travel",
      ],
      trim: true,
    },

    business: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Business",
      default: null,
    },

    description: {
      type: String,
      default: "",
      trim: true,
    },

    /*
      Human-readable location shown to customers.
      Coordinates below are generated by the location picker.
    */
    location: {
      type: String,
      required: true,
      trim: true,
    },

    latitude: {
      type: Number,
      default: null,
    },

    longitude: {
      type: Number,
      default: null,
    },

    /*
      Used by services that travel to customers.
      Example: movers, laundry pickup, etc.
    */
    serviceArea: {
      enabled: {
        type: Boolean,
        default: false,
      },
      radiusKm: {
        type: Number,
        default: null,
      },
      areas: {
        type: [String],
        default: [],
      },
    },

    /*
      Category-specific structured information.
      The exact fields depend on category.
    */
    serviceDetails: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    /*
      Availability / operating information.
    */
    availability: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    price: {
      type: String,
      default: "",
      trim: true,
    },

    image: {
      type: String,
      default: "",
    },

    images: {
      type: [String],
      default: [],
    },

    tags: {
      type: [String],
      default: [],
    },

    rating: {
      type: Number,
      default: 0,
    },

    reviews: {
      type: Number,
      default: 0,
    },

    featured: {
      type: Boolean,
      default: false,
    },

    status: {
      type: String,
      enum: ["draft", "pending", "published", "rejected"],
      default: "published",
    },

    /*
      Optional moderation information.
    */
    rejectionReason: {
      type: String,
      default: "",
    },

    adminNotes: {
      type: String,
      default: "",
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Listing", listingSchema);
